/* tslint:disable */
/* eslint-disable */
/**
 * LRMS.Web | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Команда на создание запроса на бронирование стола.
 */
export interface CreateReservationRequestCommand {
    /**
     * Имя клиента.
     */
    'customerName'?: string;
    /**
     * Номер телефона клиента.
     */
    'customerPhone'?: string;
}
/**
 * Данные текущего трека.
 */
export interface CurrentTrackDto {
    /**
     * Название.
     */
    'name'?: string;
    /**
     * Исполнители.
     */
    'authors'?: Array<string>;
    /**
     * Url картинки.
     */
    'imageUrl'?: string;
}
/**
 * Описывает ошибку, возникшую в процессе обработки команды.
 */
export interface ErrorResponse {
    /**
     * Текстовое сообщение ошибки.
     */
    'message': string;
}
/**
 * Ответ на запрос запросов на бронирование столов.
 */
export interface GetReservationRequestsResponse {
    /**
     * Коллекция запросов на бронирование столов.
     */
    'reservationRequests'?: Array<ReservationRequestDto>;
}
/**
 * Ответ на запрос получения состояния пространства.
 */
export interface GetSpaceStateResponse {
    /**
     * Состояние пространства.
     */
    'spaceState'?: SpaceStateDto;
}
/**
 * Данные запроса на бронирование стола.
 */
export interface ReservationRequestDto {
    'id'?: ReservationRequestDtoId;
    /**
     * Имя клиента.
     */
    'customerName'?: string;
    /**
     * Номер телефона клиента.
     */
    'customerPhone'?: string;
}
/**
 * Идентификатор брони.
 */
export interface ReservationRequestDtoId {
}
/**
 * Данные о состоянии пространства.
 */
export interface SpaceStateDto {
    'noiseLevel'?: SpaceStateDtoNoiseLevel;
    'workloadLevel'?: SpaceStateDtoWorkloadLevel;
    /**
     * Описание от администратора.
     */
    'description': string;
    /**
     * Текущий трек.
     */
    'currentTrack'?: CurrentTrackDto;
}
/**
 * Уровень шума в процентах.
 */
export interface SpaceStateDtoNoiseLevel {
}
/**
 * Уровень загруженности в процентах.
 */
export interface SpaceStateDtoWorkloadLevel {
}

/**
 * ReservationRequestRouteGroupApi - axios parameter creator
 */
export const ReservationRequestRouteGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Создает запрос на бронирование стола.
         * @param {CreateReservationRequestCommand} createReservationRequestCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReservationRequest: async (createReservationRequestCommand: CreateReservationRequestCommand, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createReservationRequestCommand' is not null or undefined
            assertParamExists('createReservationRequest', 'createReservationRequestCommand', createReservationRequestCommand)
            const localVarPath = `/reservation-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createReservationRequestCommand, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Удаляет запрос на бронирование стола.
         * @param {number} id Идентификатор запроса на бронирование стола.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteReservationRequest: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteReservationRequest', 'id', id)
            const localVarPath = `/reservation-requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Возвращает запросы на бронирование стола.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservationRequests: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/reservation-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReservationRequestRouteGroupApi - functional programming interface
 */
export const ReservationRequestRouteGroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReservationRequestRouteGroupApiAxiosParamCreator(configuration)
    return {
        /**
         * Создает запрос на бронирование стола.
         * @param {CreateReservationRequestCommand} createReservationRequestCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createReservationRequest(createReservationRequestCommand: CreateReservationRequestCommand, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createReservationRequest(createReservationRequestCommand, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationRequestRouteGroupApi.createReservationRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Удаляет запрос на бронирование стола.
         * @param {number} id Идентификатор запроса на бронирование стола.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteReservationRequest(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteReservationRequest(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationRequestRouteGroupApi.deleteReservationRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Возвращает запросы на бронирование стола.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReservationRequests(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetReservationRequestsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReservationRequests(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReservationRequestRouteGroupApi.getReservationRequests']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReservationRequestRouteGroupApi - factory interface
 */
export const ReservationRequestRouteGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReservationRequestRouteGroupApiFp(configuration)
    return {
        /**
         * Создает запрос на бронирование стола.
         * @param {CreateReservationRequestCommand} createReservationRequestCommand 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createReservationRequest(createReservationRequestCommand: CreateReservationRequestCommand, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createReservationRequest(createReservationRequestCommand, options).then((request) => request(axios, basePath));
        },
        /**
         * Удаляет запрос на бронирование стола.
         * @param {number} id Идентификатор запроса на бронирование стола.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteReservationRequest(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteReservationRequest(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Возвращает запросы на бронирование стола.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReservationRequests(options?: RawAxiosRequestConfig): AxiosPromise<GetReservationRequestsResponse> {
            return localVarFp.getReservationRequests(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReservationRequestRouteGroupApi - object-oriented interface
 */
export class ReservationRequestRouteGroupApi extends BaseAPI {
    /**
     * Создает запрос на бронирование стола.
     * @param {CreateReservationRequestCommand} createReservationRequestCommand 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createReservationRequest(createReservationRequestCommand: CreateReservationRequestCommand, options?: RawAxiosRequestConfig) {
        return ReservationRequestRouteGroupApiFp(this.configuration).createReservationRequest(createReservationRequestCommand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Удаляет запрос на бронирование стола.
     * @param {number} id Идентификатор запроса на бронирование стола.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteReservationRequest(id: number, options?: RawAxiosRequestConfig) {
        return ReservationRequestRouteGroupApiFp(this.configuration).deleteReservationRequest(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Возвращает запросы на бронирование стола.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getReservationRequests(options?: RawAxiosRequestConfig) {
        return ReservationRequestRouteGroupApiFp(this.configuration).getReservationRequests(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SpaceStateRouteGroupApi - axios parameter creator
 */
export const SpaceStateRouteGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Возвращает текущее состояние пространства.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpaceState: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/space-state`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SpaceStateRouteGroupApi - functional programming interface
 */
export const SpaceStateRouteGroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SpaceStateRouteGroupApiAxiosParamCreator(configuration)
    return {
        /**
         * Возвращает текущее состояние пространства.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSpaceState(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetSpaceStateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSpaceState(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SpaceStateRouteGroupApi.getSpaceState']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SpaceStateRouteGroupApi - factory interface
 */
export const SpaceStateRouteGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SpaceStateRouteGroupApiFp(configuration)
    return {
        /**
         * Возвращает текущее состояние пространства.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSpaceState(options?: RawAxiosRequestConfig): AxiosPromise<GetSpaceStateResponse> {
            return localVarFp.getSpaceState(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SpaceStateRouteGroupApi - object-oriented interface
 */
export class SpaceStateRouteGroupApi extends BaseAPI {
    /**
     * Возвращает текущее состояние пространства.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSpaceState(options?: RawAxiosRequestConfig) {
        return SpaceStateRouteGroupApiFp(this.configuration).getSpaceState(options).then((request) => request(this.axios, this.basePath));
    }
}



